# Generated by Django 5.1.6 on 2025-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.UUIDField(editable=False, unique=True)),
                ('login', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('bg', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
