# Generated by Django 5.1.6 on 2025-02-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Generation', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
